backend:
  name: github
  branch: main
  repo: Khryzen/pga
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "school"
    label: "School"
    files:
      - file: "public/content/school.json"
        label: "School Content"
        name: "school"
        fields:
          - { name: "school", label: "School Name", widget: "string" }
          - { name: "mission", label: "School Mission", widget: "string" }
          - { name: "vision", label: "School Vision", widget: "string" }
          - { name: "goals", label: "School Goals", widget: "string" }
          - { name: "logo", label: "School Logo", widget: "image" }
          - label: "Core Values"
            name: "core_values"
            widget: "list"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "image", label: "Image", widget: "image" }
              - { name: "description", label: "Description", widget: "text" }
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "public/content/homepage.json"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - { name: "headline", label: "Headline", widget: "string" }
          - { name: "subheadline", label: "Subheadline", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
          - { name: "image", label: "Hero Image", widget: "image" }
          - label: "Greetings"
            name: "greetings"
            widget: "object"
            fields:
              - { name: "headline", label: "Headline", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }
  - name: "faculty"
    label: "Faculty"
    files:
      - file: "public/content/faculty.json"
        label: "Faculty Content"
        name: "faculty"
        fields:
          - { name: "faculty_header", label: "Faculty Header", widget: "string" }
          - { name: "faculty_description", label: "Faculty Description", widget: "text" }
          - { name: "teaching_header", label: "Teaching Staff Header", widget: "string" }
          - { name: "teaching_description", label: "Teaching Staff Description", widget: "text" }
          - { name: "admin_header", label: "Admin Header", widget: "string" }
          - { name: "admin_description", label: "Admin Description", widget: "text" }
          - label: "Teaching Faculty"
            name: "teaching_faculty"
            widget: "list"
            fields:
              - {name: "image", label: "Image", widget: "image"}
              - {name: "name", label: "Name", widget: "string"}
              - {name: "designation", label: "Designation", widget: "string"}
              - {name: "description", label: "Description", widget: "text"}
          - label: "Non-Teaching Faculty"
            name: "non_teaching_faculty"
            widget: "list"
            fields:
              - {name: "image", label: "Image", widget: "image"}
              - {name: "name", label: "Name", widget: "string"}
              - {name: "designation", label: "Designation", widget: "string"}
              - {name: "description", label: "Description", widget: "text"}